env:
  es6: true
  browser: true
  commonjs: true
  jest: true

extends: ['htmlacademy/es6', 'plugin:react/recommended']

parser: 'babel-eslint'

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module

plugins: ['react', 'babel']

settings:
  react:
    version: '16'

rules:
  no-invalid-this: 0
  babel/no-invalid-this: 1
